### ISSUE TITLE
Examples indocumentation not working

### ISSUE THREAD

**Issue by rami-dabain** [cosmos/vanity#7]
In https://docs.cosmos.network/master/run-node/txs.html#programmatically-with-go

the resulting TX "on mainnet" looks like this:

` {"body":{"messages":[{"@type":"/cosmos.bank.v1beta1.MsgSend","from_address":"sent106ur8d0lnh34alqzrf6ajlhy2cryymyqqyn7w7","to_address":"sent1wqqygaeu9asyv04nnhfm9y7ya4azmr54mr39t4","amount":[{"denom":"uatom","amount":"1000000"}]}],"memo":"vpn test memo","timeout_height":"5","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[],"fee":{"amount":[{"denom":"uatom","amount":"20000"}],"gas_limit":"20000","payer":"","granter":""}},"signatures":[]}`

resulting in the server response with :
`code:18 raw_log:"must contain at least one message: invalid request" `

as it expects `msg` (or `msgs` not sure) but it receives `messages` (both in json and protobuf)

**Comment by tac0turtle** [comment]
the documentation has been moved to the cosmos-sdk. If you are still running into issues please feel free to open an issue there
